version = 1.24.0
group = dev.walgo
title = Java DTO generator
description = Flexible DTO Java classes generator. Generate classes from database metadata (schema).

guavaVersion = 33.5.0-jre
commonsCliVersion = 1.11.0
commonsLangVersion = 3.20.0
pebbleVersion = 4.1.1
slf4jVersion = 2.0.16
logbackVersion = 1.5.32
gsonVersion = 2.13.2
immutablesVersion = 2.12.1
assertjVersion=3.26.3
